alias g='git'
alias ga='git add'
alias gc='git commit'
alias gco='git checkout'
alias gst='git status'
alias gl='git pull'
alias gp='git push'

alias be='bundle exec'
alias bi='bundle install'
alias bu='bundle update'

alias dc='docker-compose'
alias dcu='docker-compose up'
alias dcd='docker-compose down'
alias dcr='docker-compose run'
